### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by excalibur1234** [trollixx/quickterminal#11]
i just tried to run different variations of a command and always receive the same error message:
`
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
[1]    2776 segmentation fault (core dumped)  qt -e "youtube-dl https://www.youtube.com/watch\?v\=CJfY9BqeKCg"
`

i run arch linux and have the latest qtermwidget-git installed. is this the reason i get a core dump?

**Comment by trollixx** [comment]
I have just rebuilt both qtermwidget and quickterminal, and I can't reproduce the crash. Something else might be triggering the segfault. If you have some time, you could try to debug it, and find the real cause.
